## Convolutional and Max Pooling Layers

In order to get a better understanding of convolutional and max pooling layers, in this homework you will implement these two layers from scratch without PyTorch! Fill out the two python functions below and then run the `assert` statements in order to check that your code works :)

Homework idea based off of assignment 2 from CS231N

In this homework, you are only allowed to use the `numpy` package. I think this homework is fairly hard so please feel free to discuss with classmates on piazza. However, please post at most pseudocode for a subproblem and please do not post an answer.  

In [1]:
import numpy as np

![ConvURL](https://raw.githubusercontent.com/iamaaditya/iamaaditya.github.io/master/images/conv_arithmetic/full_padding_no_strides_transposed.gif "conv")

Recall the convolution layer. In this gif, we slide a 3 x 3 (dark blue) filter along the input image (light blue) in order to produce the (green) output image. There is no padding, and the stride is 1. To produce a green value, we dot a portion of the input image with the filter weights and add the bias ($Wx + b$).

### 1. Convolutional Layer

Implement `conv_forward_naive`, which takes in the input data, the weight matrix, the bias vector, and parameters about this convolutional layer.

Hint: It may be a good idea to extract out N, C, H, W, F, etc. into variables for easier use.

Hint2: How many `for` loops do you need?


In [2]:
def conv_forward_naive(x, w, b, conv_param):
    """
    A naive implementation of the forward pass for a convolutional layer.

    The input consists of N data points, each with C channels, height H and
    width W. We convolve each input with F different filters, where each filter
    spans all C channels and has height HH and width WW.

    Input:
    - x: Input data of shape (N, C, H, W)
    - w: Filter weights of shape (F, C, HH, WW)
    - b: Biases, of shape (F,)
    - conv_param: A dictionary with the following keys:
      - 'stride': The number of pixels between adjacent receptive fields in the
        horizontal and vertical directions.
      - 'pad': The number of pixels that will be used to zero-pad the input.

    Returns:
    - out: Output data, of shape (N, F, H', W') where H' and W' are given by
      H' = 1 + (H + 2 * pad - HH) / stride
      W' = 1 + (W + 2 * pad - WW) / stride
    """
    
    print(np.shape(w)) 
    print(np.shape(x))
    print(np.shape(b))
    out = None
    
    stride = conv_param['stride']
    pad = conv_param['pad']

    n = x.shape[0]
    c = x.shape[1]
    h = x.shape[2]
    width = x.shape[3]
    
    f = w.shape[0]
    hh = w.shape[2]
    ww = w.shape[3]

    h_prime = int(1 + (h + 2 * pad - hh) / stride)
    w_prime = int(1 + (width + 2 * pad - ww) / stride)

    npad = ((0, 0), (0, 0), (pad, pad), (pad, pad))
    x_pad = np.pad(x, pad_width=npad, mode='constant', constant_values=0) #padded x

    out = np.zeros((n, f, h_prime, w_prime)) #initialized
   

    ###########################################################################
    # TODO: Implement the convolutional forward pass.                         #
    # Hint: you can use the function np.pad for padding. We did this for you. #
    # We also defined all the salient variables. The remaining part of this   #
    # problem is creating the for loops and stitching the variables together. #
    # Start by making sure you understand every portion of the above code.    #
    # Hint2: Add the appropriate bias to each term in each convolution        #
    ###########################################################################
    
    #Your code here!
    
    for a in range(n):
        for z in range(f): #for each filter layer,
            for j in range(h_prime):
                for i in range(w_prime):
                    out[a][z][j][i] = 0
                    for k in range(c):
                       
                        dot = np.multiply(x_pad[a][k][i*stride:i*stride+hh,j*stride:j*stride+ww],w[z][k])            
                        #print(np.shape(dot))
                        _sum = sum(sum(dot))
                        #print(_sum)
                        out[a][z][j][i] += _sum
                    out[a][z][j][i]+=b[z]
                        
    
    
    ###########################################################################
    #                             END OF YOUR CODE                            #
    ###########################################################################
    return out

### 2. Max Pooling Layer

Implement this max pooling layer python function.

Hint: This should be pretty similar to the convolution layer above.

Hint2: It will be useful to calculate what the expected output dimensions will be. If you need help with this, feel free to chat a friend in the DeCal or a staff member.

In [3]:
def max_pool_forward_naive(x, pool_param):
    """
    A naive implementation of the forward pass for a max pooling layer.

    Inputs:
    - x: Input data, of shape (N, C, H, W)
    - pool_param: dictionary with the following keys:
      - 'pool_height': The height of each pooling region
      - 'pool_width': The width of each pooling region
      - 'stride': The distance between adjacent pooling regions

    Returns:
    - out: Output data
    """
    out = None
    ###########################################################################
    # TODO: Implement the max pooling forward pass                            #
    ###########################################################################
   

    ###########################################################################
    #                             END OF YOUR CODE                            #
    ###########################################################################
    return out

## 3. Check your answers!

If your code passes these assert statements, you should be good to go!

In [4]:
### TESTING OF CONV LAYER

np.random.seed(42)
x = np.random.normal(size=[1, 3, 11, 11])
w = np.random.normal(size=[2, 3, 5, 5])
b = np.random.normal(size=[2])
conv_param = {'stride': 3, 'pad': 3}
result = conv_forward_naive(x, w, b, conv_param)
print(result)
assert np.allclose(result, np.array([[[[ 3.13783023, -5.32751231, -1.71460357, -3.22003339,  3.27438643],
   [-3.39967189,  2.39404469, -4.2126656,   4.80549383, -1.40836569],
   [-0.67034629, -7.53964901, -8.11099708, -6.24694429, -1.82490217],
   [ 0.75443863, -4.92723594,  3.06248213, -2.37856105,  8.86919592],
   [-7.34305417,  3.18673458,  6.33894349, -1.72720915,  0.77468496]],

  [[-2.61841618,  3.32434937, -0.93731549,  3.27477707,  0.63882942],
   [-6.49573417, -0.33254641,  0.93942528, 15.50203272, -3.9097889 ],
   [ 6.75564931, -3.56840551,  4.27588487, 12.28841061, -6.50030743],
   [ 0.59184847,  2.48632324,  4.99003361,  5.70073028, -2.3884948 ],
   [-3.98443104,  1.29550344, -3.46922113, -2.73797865, -1.05677199]]]]))

(2, 3, 5, 5)
(1, 3, 11, 11)
(2,)
[[[[ 3.13783023 -5.32751231 -1.71460357 -3.22003339  3.27438643]
   [-3.39967189  2.39404469 -4.2126656   4.80549383 -1.40836569]
   [-0.67034629 -7.53964901 -8.11099708 -6.24694429 -1.82490217]
   [ 0.75443863 -4.92723594  3.06248213 -2.37856105  8.86919592]
   [-7.34305417  3.18673458  6.33894349 -1.72720915  0.77468496]]

  [[-2.61841618  3.32434937 -0.93731549  3.27477707  0.63882942]
   [-6.49573417 -0.33254641  0.93942528 15.50203272 -3.9097889 ]
   [ 6.75564931 -3.56840551  4.27588487 12.28841061 -6.50030743]
   [ 0.59184847  2.48632324  4.99003361  5.70073028 -2.3884948 ]
   [-3.98443104  1.29550344 -3.46922113 -2.73797865 -1.05677199]]]]


In [5]:
### TESTING OF MAX POOL LAYER
np.random.seed(45)
x = np.random.normal(size=(1, 3, 8, 8))
pool_param = {'pool_height': 5, 'pool_width': 5, 'stride': 3}
result = max_pool_forward_naive(x, pool_param)

assert np.allclose(result, np.array([[[[ 2.24808957,  2.24808957],
         [ 2.24808957,  2.24808957]],

        [[ 1.21650079,  1.81659525],
         [ 2.44659327,  1.76020474]],

        [[ 2.99363398,  1.62741182],
         [ 1.67882964,  1.67882964]]]]) )

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''